# Generated by Django 5.0.4 on 2024-05-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('related_link', models.URLField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog')),
                ('data_time', models.DateTimeField()),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
    ]
